# Maven build container
FROM maven:3.8.6-openjdk-11 AS maven_build
WORKDIR /tmp/

COPY /utils-service/src /tmp/utils-service/src
COPY /utils-service/pom.xml /tmp/utils-service
RUN mvn -f /tmp/utils-service/pom.xml clean install -Dmaven.test.skip=true

COPY /payment-service/src /tmp/payment-service/src
COPY /payment-service/pom.xml /tmp/payment-service
RUN mvn -f /tmp/payment-service/pom.xml clean package install:install-file -Dfile=/tmp/utils-service/target/utils-service-0.0.1-SNAPSHOT.jar -DgroupId=com.jober -DartifactId=utils-service -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -DgeneratePom=true -Dmaven.test.skip=true

#pull base image
FROM eclipse-temurin:11-jre
COPY --from=maven_build /tmp/payment-service/target/*.jar /app.jar
EXPOSE 2006
ENV JAVA_OPTS="-Xms256m -Xmx512m"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=true -jar /app.jar" ]

