#version: '3.9'
#
#networks:
#  my-networks:
#    driver: bridge
#services:
#  discovery-server:
#    image: discovery-server-dev
#    container_name: discovery-server-container-dev
#    build:
#      context: discovery-server
#      dockerfile: ./Dockerfile
#    environment:
#      EUREKA_PORT: '2001'
#      PORT: '2001'
#    ports:
#      - '2001:2001'
#    networks:
#      my-networks:
#        aliases:
#          - 'discovery-server'
#  api-gateway:
#    image: api-gateway-dev
#    container_name: api-gateway-container-dev
#    build:
#      context: api-gateway
#      dockerfile: ./Dockerfile
#    environment:
#      EUREKA_URL: discovery-server
#      DOMAIN_FE: https://test1.jober.com.vn/
#      EUREKA_PORT: '2001'
#      PORT: '2000'
#    depends_on:
#      - discovery-server
#    restart: on-failure
#    ports:
#      - '2000:2000'
#    networks:
#      - my-networks
#  authorization-server:
#    image: authorization-server-dev
#    container_name: authorization-server-container-dev
#    build:
#      context: authorization-server
#      dockerfile: ./Dockerfile
#    environment:
#      EUREKA_URL: discovery-server
#      EUREKA_PORT: '2001'
#      PORT: '2004'
#      DB_HOST: 113.177.27.200
#      DB_PORT: 5433
#      DB_NAME: jober_test
#      DB_USER: admin
#      DB_PASS: juile2022
#    depends_on:
#      - discovery-server
#    restart: on-failure
#    ports:
#      - '2004:2004'
#    networks:
#      my-networks:
#        aliases:
#          - 'authorization-server'
#  user-service:
#    image: user-service-dev
#    container_name: user-service-container-dev
#    build:
#      context: .
#      dockerfile: ./Dockerfile-user
#    environment:
#      REDIS_HOST: 113.177.27.200
#      REDIS_PORT: 6379
#      REDIS_PASS: julie2022
#      EUREKA_URL: discovery-server
#      AUTH_URL: authorization-server-container-dev
#      PAYMENT_URL: payment-service-container-dev
#      SEARCH_URL: search-service-container-dev
#      EUREKA_PORT: '2001'
#      AUTH_PORT: '2004'
#      GATEWAY_PORT: '2000'
#      PORT: '2005'
#      PAYMENT_SERVICE_PORT: '2006'
#      SEARCH_SERVICE_PORT: '2002'
#      FE_DOMAIN: https://dev.jober.com.vn
#      REDIRECT_URI: https://api-dev.jober.com.vn/login/oauth2/code/google
#      DB_HOST: 113.177.27.200
#      DB_PORT: 5433
#      DB_NAME: jober_test
#      DB_USER: admin
#      DB_PASS: juile2022
#      FILE_PATH: /tmp/files/
#    depends_on:
#      - discovery-server
#      - authorization-server
#      # - utils-service
#    restart: on-failure
#    ports:
#      - '2005:2005'
#    networks:
#      - my-networks
#    volumes:
#      - /home/tony/data/jober_v2/file:/tmp/files
#  search-service:
#    image: search-service-dev
#    container_name: search-service-container-dev
#    build:
#      context: .
#      dockerfile: ./Dockerfile-search
#    environment:
#      REDIS_HOST: 113.177.27.200
#      REDIS_PORT: 6379
#      REDIS_PASS: julie2022
#      EUREKA_URL: discovery-server
#      AUTH_URL: authorization-server-container-dev
#      BE_URL: https://api.jober.com.vn
#      EUREKA_PORT: '2001'
#      AUTH_PORT: '2004'
#      GATEWAY_PORT: '2000'
#      PORT: '2002'
#      DB_HOST: 113.177.27.200
#      DB_PORT: 5433
#      DB_NAME: jober_test
#      DB_USER: admin
#      DB_PASS: juile2022
#    depends_on:
#      - discovery-server
#      - authorization-server
#      #  - utils-service
#    restart: on-failure
#    ports:
#      - '2002:2002'
#    networks:
#      - my-networks
#
#  payment-service:
#    image: payment-service-dev
#    container_name: payment-service-container-dev
#    build:
#      context: .
#      dockerfile: ./Dockerfile-payment
#    environment:
#      REDIS_HOST: 113.177.27.200
#      REDIS_PORT: 6379
#      REDIS_PASS: julie2022
#      EUREKA_URL: discovery-server
#      AUTH_URL: authorization-server-container-dev
#      USER_URL: user-service-container-dev
#      AUTH_PORT: '2004'
#      GATEWAY_PORT: '2000'
#      EUREKA_PORT: '2001'
#      USER_SERVICE_PORT: '2005'
#      PORT: '2006'
#      FE_DOMAIN: https://dev.jober.com.vn
#      DB_HOST: 113.177.27.200
#      DB_PORT: 5433
#      DB_NAME: jober_test
#      DB_USER: admin
#      DB_PASS: juile2022
#    depends_on:
#      - discovery-server
#      - authorization-server
#    restart: on-failure
#    ports:
#      - '2006:2006'
#    networks:
#      - my-networks
#  configuration-service:
#    image: configuration-service-dev
#    container_name: configuration-service-container-dev
#    build:
#      context: .
#      dockerfile: ./Dockerfile-configuration
#    environment:
#      REDIS_HOST: 113.177.27.200
#      REDIS_PORT: 6379
#      REDIS_PASS: julie2022
#      EUREKA_URL: discovery-server
#      AUTH_URL: authorization-server-container-dev
#      USER_URL: user-service-container-dev
#      EUREKA_PORT: '2001'
#      AUTH_PORT: '2004'
#      GATEWAY_PORT: '2000'
#      PORT: '2007'
#      USER_SERVICE_PORT: '2005'
#      DB_HOST: 113.177.27.200
#      DB_PORT: 5433
#      DB_NAME: jober_test
#      DB_USER: admin
#      DB_PASS: juile2022
#    depends_on:
#      - discovery-server
#      - authorization-server
#    restart: on-failure
#    ports:
#      - '2007:2007'
#    networks:
#      - my-networks
##  utils-service:
##    image: utils-service
##    container_name: utils-service-container-dev
##    build:
##      context: .
##      dockerfile: ./Dockerfile-payment
##    environment:
##      EUREKA_URL: discovery-server
##      AUTH_URL: authorization-server-container
##      EUREKA_PORT: '2001'
##      PORT: '2006'
##    depends_on:
##      - discovery-server
##      - authorization-server
##    restart: on-failure
##    ports:
##      - '2006:2006'
##    networks:
##      - my-networks
