version: '3.9'

networks:
  my-networks:
    driver: bridge

services:
  postgres:
    image: ankane/pgvector:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres-container
    environment:
      POSTGRES_DB: jober_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: juile2022
    ports:
      - '5433:5432'
    networks:
      - my-networks

  redis:
    image: redis:6
    container_name: redis-container
    command: redis-server --requirepass julie2022
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - my-networks

  discovery-server:
    image: discovery-server
    container_name: discovery-server-container
    build:
      context: discovery-server
      dockerfile: ./Dockerfile
    environment:
      EUREKA_PORT: '2001'
      PORT: '2001'
    ports:
      - '2001:2001'
    networks:
      my-networks:
        aliases:
          - 'discovery-server'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2001/eureka/apps"]
      interval: 30s
      retries: 5
      start_period: 30s

  api-gateway:
    image: api-gateway
    container_name: api-gateway-container
    build:
      context: api-gateway
      dockerfile: ./Dockerfile
    environment:
      EUREKA_URL: discovery-server
      DOMAIN_FE: https://test1.jober.com.vn/
      EUREKA_PORT: '2001'
      PORT: '2000'
    depends_on:
      - discovery-server
    restart: on-failure
    ports:
      - '2000:2000'
    networks:
      - my-networks

  authorization-server:
    image: authorization-server
    container_name: authorization-server-container
    build:
      context: authorization-server
      dockerfile: ./Dockerfile
    environment:
      EUREKA_URL: discovery-server
      EUREKA_PORT: '2001'
      PORT: '2004'
      DB_HOST: postgres-container
      DB_PORT: 5432
      DB_NAME: jober_test
      DB_USER: admin
      DB_PASS: juile2022
    depends_on:
      - discovery-server
      - postgres
    restart: on-failure
    ports:
      - '2004:2004'
    networks:
      my-networks:
        aliases:
          - 'authorization-server'

  user-service:
    image: user-service
    container_name: user-service-container
    build:
      context: .
      dockerfile: ./Dockerfile-user
    environment:
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      REDIS_PASS: julie2022
      EUREKA_URL: discovery-server
      AUTH_URL: authorization-server-container
      PAYMENT_URL: payment-service-container
      SEARCH_URL: search-service-container
      EUREKA_PORT: '2001'
      AUTH_PORT: '2004'
      GATEWAY_PORT: '2000'
      PORT: '2005'
      PAYMENT_SERVICE_PORT: '2006'
      SEARCH_SERVICE_PORT: '2002'
      FE_DOMAIN: http://localhost:4200
      REDIRECT_URI: http://localhost:2000/login/oauth2/code/google
      DB_HOST: postgres-container
      DB_PORT: 5432
      DB_NAME: jober_test
      DB_USER: admin
      DB_PASS: juile2022
    depends_on:
      - discovery-server
      - authorization-server
      - postgres
      - redis
    restart: on-failure
    ports:
      - '2005:2005'
    networks:
      - my-networks
    volumes:
      - ./local-files:/tmp/files

  search-service:
    image: search-service
    container_name: search-service-container
    build:
      context: .
      dockerfile: ./Dockerfile-search
    environment:
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      REDIS_PASS: julie2022
      EUREKA_URL: discovery-server
      AUTH_URL: authorization-server-container
      BE_URL: https://api.jober.com.vn
      EUREKA_PORT: '2001'
      AUTH_PORT: '2004'
      GATEWAY_PORT: '2000'
      PORT: '2002'
      DB_HOST: postgres-container
      DB_PORT: 5432
      DB_NAME: jober_test
      DB_USER: admin
      DB_PASS: juile2022
    depends_on:
      - discovery-server
      - authorization-server
      - postgres
      - redis
    restart: on-failure
    ports:
      - '2002:2002'
    networks:
      - my-networks

  payment-service:
    image: payment-service
    container_name: payment-service-container
    build:
      context: .
      dockerfile: ./Dockerfile-payment
    environment:
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      REDIS_PASS: julie2022
      EUREKA_URL: discovery-server
      AUTH_URL: authorization-server-container
      USER_URL: user-service-container
      AUTH_PORT: '2004'
      GATEWAY_PORT: '2000'
      EUREKA_PORT: '2001'
      USER_SERVICE_PORT: '2005'
      PORT: '2006'
      FE_DOMAIN: http://localhost:4200
      DB_HOST: postgres-container
      DB_PORT: 5432
      DB_NAME: jober_test
      DB_USER: admin
      DB_PASS: juile2022
    depends_on:
      - discovery-server
      - authorization-server
      - postgres
      - redis
    restart: on-failure
    ports:
      - '2006:2006'
    networks:
      - my-networks

  configuration-service:
    image: configuration-service
    container_name: configuration-service-container
    build:
      context: .
      dockerfile: ./Dockerfile-configuration
    environment:
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      REDIS_PASS: julie2022
      EUREKA_URL: discovery-server
      AUTH_URL: authorization-server-container
      EUREKA_PORT: '2001'
      AUTH_PORT: '2004'
      GATEWAY_PORT: '2000'
      PORT: '2007'
      DB_HOST: postgres-container
      DB_PORT: 5432
      DB_NAME: jober_test
      DB_USER: admin
      DB_PASS: juile2022
    depends_on:
      - discovery-server
      - authorization-server
      - postgres
      - redis
    restart: on-failure
    ports:
      - '2007:2007'
    networks:
      - my-networks

volumes:
  postgres-data:
  redis-data:
