pipeline {
    environment {
        PATH = "/usr/local/bin"
    }
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: 'http://localhost:2033/SVC_D3/jober.git',
                credentialsId: '11111',
                branch: 'develop'
            }
        }
        stage('Build') {
            steps {
                sh  'docker-compose build'
            }
        }
        stage('Deploy') {
            steps {
                sh  'docker-compose up -d'
            }
        }
    }
}