spring:
  flyway:
    enabled: false
  #  profiles: production
  application:
    name: search-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:}
  cache:
    enabled: false
    type: redis
    cache-names: search
    redis:
      key-prefix: search
server:
  port: ${PORT:2002}
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:${EUREKA_PORT:2001}/eureka/
security:
  oauth2:
    client:
      client-id: ${AUTH_CLIENTID:clientId}
      client-secret: ${AUTH_SECRET:nhung}
    resource:
      token-info-uri: http://${AUTH_URL:localhost}:${AUTH_PORT:2004}/oauth/check_token

#
#spring:
#  flyway:
#    enabled: false
#
#  application:
#    name: search-service
#
#  redis:
#    host: ${REDIS_HOST:redis-container}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASS:}
#
#  cache:
#    enabled: false
#    type: redis
#    cache-names: search
#    redis:
#      key-prefix: search
#
#server:
#  port: ${PORT:2002}
#
#eureka:
#  instance:
#    preferIpAddress: 'true'
#  client:
#    fetchRegistry: 'true'
#    registerWithEureka: 'true'
#    serviceUrl:
#      defaultZone: http://${EUREKA_URL:discovery-server}:${EUREKA_PORT:2001}/eureka/
#
#security:
#  oauth2:
#    client:
#      client-id: ${AUTH_CLIENTID:clientId}
#      client-secret: ${AUTH_SECRET:nhung}
#    resource:
#      token-info-uri: http://${AUTH_URL:authorization-server}:${AUTH_PORT:2004}/oauth/check_token
