google.api.key=AIzaSyAfPzO_h8A4JtJYdEipFR5HACevboh0dhI
auth-server-uri=http://${AUTH_URL:localhost}:${AUTH_PORT:2004}/
user-server-uri = http://${USER_URL:localhost}:${USER_SERVICE_PORT:2005}
#spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jober}
#spring.datasource.username=${DB_USER:nhung}
#spring.datasource.password=${DB_PASS:nhung}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:jober_test}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:juile2022}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect
