spring.datasource.url=jdbc:postgresql://localhost:5433/jober_prod
spring.datasource.username=admin
spring.datasource.password=juile2022
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.connectionTimeout=30000 
#   Th?i gian tính b?ng mili giây mà client s? ch? m?t connection t? pool
spring.datasource.idleTimeout=600000 
#  Thi?t l?p th?i gian t?i ?a mà k?t n?i ???c phép ?? ? ch? ?? ch? trong pool
spring.datasource.maxLifetime=1800000 
#   Tu?i th? t?i ?a c?a m?t connection trong pool

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect
