auth-server-uri = http://authorization-server-container:${AUTH_PORT:2004}/
user-server-uri = http://user-service-container:${USER_SERVICE_PORT:2005}
fe-domain=${FE_DOMAIN:http://localhost:4200}
google.api.key=AIzaSyAfPzO_h8A4JtJYdEipFR5HACevboh0dhI

spring.datasource.url=jdbc:postgresql://localhost:5433/jober_prod
spring.datasource.username=admin
spring.datasource.password=juile2022
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect
