-- Insert sample organizations into the organization table
INSERT INTO organization (name, des, creationdate, updatedate, active, avatar) VALUES
('NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN KỸ THƯƠNG VIỆT NAM', 'Ngân hàng thương mại hàng đầu Việt Nam', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/bank.png'),
('NGÂN HÀNG TMCP VIỆT NAM THỊNH VƯỢNG', 'Ngân hàng phát triển nhanh nhất Việt Nam', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/bank.png'),
('NOVALAND GROUP CORP', 'Tập đoàn bất động sản hàng đầu', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/real-estate.png'),
('TẬP ĐOÀN CÔNG NGHIỆP - VIỄN THÔNG QUÂN ĐỘI', 'Tập đoàn viễn thông lớn nhất Việt Nam', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/phone.png'),
('CÔNG TY TNHH BẢO HIỂM NHÂN THỌ AIA (VIỆT NAM)', 'Công ty bảo hiểm nhân thọ hàng đầu', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/insurance.png'),
('NGÂN HÀNG TMCP HÀNG HẢI VIỆT NAM (MSB)', 'Ngân hàng thương mại cổ phần', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/bank.png'),
('CÔNG TY CỔ PHẦN HẠ TẦNG VIỄN THÔNG CMC', 'Công ty viễn thông và công nghệ', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/phone.png'),
('CÔNG TY CỔ PHẦN TẬP ĐOÀN FLC', 'Tập đoàn du lịch và bất động sản', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/hotel.png'),
('TẬP ĐOÀN NOVAON', 'Tập đoàn công nghệ và truyền thông', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/computer.png'),
('CÔNG TY CỔ PHẦN FPT', 'Tập đoàn công nghệ thông tin hàng đầu', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/computer.png'),
('CÔNG TY TNHH UNILEVER VIỆT NAM', 'Công ty hàng tiêu dùng đa quốc gia', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/shopping-cart.png'),
('CÔNG TY CỔ PHẦN SABECO', 'Tập đoàn bia rượu nước giải khát', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/beer.png'),
('CÔNG TY CỔ PHẦN VINAMILK', 'Tập đoàn sữa hàng đầu Việt Nam', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/milk.png'),
('CÔNG TY CỔ PHẦN VINGROUP', 'Tập đoàn đa ngành hàng đầu Việt Nam', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/company.png'),
('CÔNG TY CỔ PHẦN MASAN GROUP', 'Tập đoàn tiêu dùng và bán lẻ', NOW(), NOW(), 1, 'https://img.icons8.com/color/64/shopping-bag.png');

-- Insert some sample jobs for these organizations to make them "standout"
INSERT INTO job (organizationid, title, description, active, creationdate, updatedate) VALUES
(1, 'Chuyên viên tín dụng', 'Xử lý hồ sơ tín dụng cho khách hàng', 1, NOW(), NOW()),
(1, 'Chuyên viên bán hàng', 'Tư vấn sản phẩm ngân hàng', 1, NOW(), NOW()),
(1, 'Kế toán trưởng', 'Quản lý kế toán và tài chính', 1, NOW(), NOW()),
(2, 'Chuyên viên phân tích tài chính', 'Phân tích và đánh giá tài chính', 1, NOW(), NOW()),
(2, 'Chuyên viên marketing', 'Phát triển chiến lược marketing', 1, NOW(), NOW()),
(3, 'Kỹ sư xây dựng', 'Thiết kế và giám sát dự án', 1, NOW(), NOW()),
(3, 'Chuyên viên bất động sản', 'Tư vấn và bán bất động sản', 1, NOW(), NOW()),
(4, 'Kỹ sư viễn thông', 'Phát triển hệ thống viễn thông', 1, NOW(), NOW()),
(4, 'Chuyên viên IT', 'Phát triển phần mềm và hệ thống', 1, NOW(), NOW()),
(5, 'Chuyên viên bảo hiểm', 'Tư vấn và bán bảo hiểm', 1, NOW(), NOW()),
(5, 'Chuyên viên tư vấn tài chính', 'Tư vấn sản phẩm tài chính', 1, NOW(), NOW()),
(6, 'Chuyên viên ngân hàng', 'Xử lý giao dịch ngân hàng', 1, NOW(), NOW()),
(6, 'Chuyên viên khách hàng', 'Chăm sóc khách hàng doanh nghiệp', 1, NOW(), NOW()),
(7, 'Kỹ sư mạng', 'Thiết kế và triển khai mạng', 1, NOW(), NOW()),
(7, 'Chuyên viên viễn thông', 'Vận hành hệ thống viễn thông', 1, NOW(), NOW()),
(8, 'Chuyên viên du lịch', 'Tổ chức tour và sự kiện', 1, NOW(), NOW()),
(8, 'Chuyên viên khách sạn', 'Quản lý dịch vụ khách sạn', 1, NOW(), NOW()),
(9, 'Lập trình viên', 'Phát triển ứng dụng web', 1, NOW(), NOW()),
(9, 'Chuyên viên marketing số', 'Phát triển chiến lược digital marketing', 1, NOW(), NOW()),
(10, 'Kỹ sư phần mềm', 'Phát triển phần mềm doanh nghiệp', 1, NOW(), NOW()),
(10, 'Chuyên viên AI', 'Phát triển trí tuệ nhân tạo', 1, NOW(), NOW());
