pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: 'http://113.177.27.200:2033/SVC_D3/jober-FE.git',
                credentialsId: '11111',
                branch: 'develop'
            }
        }
        stage('Build') {
            steps {
                bat  'docker build -t joberfe -f .\\Dockerfile .'
            }
        }
        stage('Deploy') {
            steps {
                bat  'docker rm -f fe'
                bat 'docker run -d -p 4200:80 --name fe joberfe'
            }
        }
    }
}
