-- Script để cập nhật icon cho các ngành nghề nổi bật
-- Thay thế URL icon cũ bằng link ảnh đẹp hơn

-- Kinh doanh - Bán hàng (Price tag với $)
UPDATE jobdefault SET icon = 'https://img.icons8.com/color/64/price-tag.png' 
WHERE LOWER(name) LIKE '%kinh doanh%' OR LOWER(name) LIKE '%bán hàng%' OR LOWER(name) LIKE '%sale%';

-- Marketing - PR - Quảng cáo
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0zIDlWMTVIN1Y5SDNaTTEwIDZIMjBWMThIMTBWNloiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%marketing%' OR LOWER(name) LIKE '%truyền thông%' OR LOWER(name) LIKE '%quảng cáo%' OR LOWER(name) LIKE '%telesales%';

-- Chăm sóc khách hàng
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiA0QzE1LjMxIDQgMTggNi42OSAxOCAxMFYxNEMxOCAxNy4zMSAxNS4zMSAyMCAxMiAyMEgxMFYxNkgxMkMxMy4xIDE2IDE0IDE1LjEgMTQgMTRWMTBDMTQgOC45IDEzLjEgOCAxMiA4UzEwIDguOSAxMCAxMFYxNEMxMCAxNS4xIDEwLjkgMTYgMTIgMTZIMTNWMThIMTJaIi8+Cjwvc3ZnPgo8L3N2Zz4=' 
WHERE LOWER(name) LIKE '%chăm sóc%' OR LOWER(name) LIKE '%customer%' OR LOWER(name) LIKE '%tư vấn%';

-- Nhân sự - Hành chính
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yMCA2SDE2VjRIMThWNEg2VjZIMlYyMEgyMlY2Wk0xNiA4SDE4VjE4SDE2VjhaTTggOEgxMFYxOEg4VjhaIi8+Cjwvc3ZnPgo8L3N2Zz4=' 
WHERE LOWER(name) LIKE '%nhân sự%' OR LOWER(name) LIKE '%hành chính%' OR LOWER(name) LIKE '%văn phòng%' OR LOWER(name) LIKE '%tuyển sinh%';

-- Công nghệ Thông tin
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDRIMjJWMjBIMlY0Wk00IDZIMjBWMThINFY2Wk0xMCAyMEgxNFYyMkgxMFYyMFoiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%công nghệ%' OR LOWER(name) LIKE '%it%' OR LOWER(name) LIKE '%lập trình%' OR LOWER(name) LIKE '%devops%' OR LOWER(name) LIKE '%programmer%' OR LOWER(name) LIKE '%developer%' OR LOWER(name) LIKE '%php%' OR LOWER(name) LIKE '%.net%';

-- Tài chính - Ngân hàng
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDZIMjJWMjBIMlY2Wk00IDhIMjBWMThINFY4Wk02IDEwSDhWMTZINlYxMFpNMTAgMTBIMTJWMTZIMTBWMTAiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%tài chính%' OR LOWER(name) LIKE '%ngân hàng%' OR LOWER(name) LIKE '%kế toán%' OR LOWER(name) LIKE '%kiểm toán%' OR LOWER(name) LIKE '%thuế%' OR LOWER(name) LIKE '%techcombank%';

-- Bất động sản
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiA0TDIwIDEyVjIwSDE2VjE0SDhWMjBINFYxMkwxMiA0WiIvPgo8L3N2Zz4KPC9zdmc+' 
WHERE LOWER(name) LIKE '%bất động sản%' OR LOWER(name) LIKE '%nhà đất%' OR LOWER(name) LIKE '%real estate%';

-- Y tế - Dược
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiAyQzE3LjUyIDIgMjIgNi40OCAyMiAxMkMyMiAxNy41MiAxNy41MiAyMiAxMiAyMkM2LjQ4IDIyIDIgMTcuNTIgMiAxMkMyIDYuNDggNi40OCAyIDEyIDJaTTEzIDEzSDIwVjExSDEzVjRIMTFWMTFINFYxM0gxMVYyMEgxM1YxM1oiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%y tế%' OR LOWER(name) LIKE '%dược%' OR LOWER(name) LIKE '%bác sĩ%' OR LOWER(name) LIKE '%y tá%';

-- Giáo dục - Đào tạo
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiA0TDIwIDEyVjIwSDE2VjE0SDhWMjBINFYxMkwxMiA0Wk0xMiA2TDYgMTJIMTBWMTZIMTRWMTJIMThMMTIgNloiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%giáo dục%' OR LOWER(name) LIKE '%đào tạo%' OR LOWER(name) LIKE '%trường học%' OR LOWER(name) LIKE '%học viên%';

-- Sản xuất - Công nghiệp
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDJIMjJWMjBIMlYyWk00IDRIMjBWMThINFY0Wk02IDZIMThWMTZINlY2Wk04IDhIMTZWMTRIOFY4WiIvPgo8L3N2Zz4KPC9zdmc+' 
WHERE LOWER(name) LIKE '%sản xuất%' OR LOWER(name) LIKE '%công nhân%' OR LOWER(name) LIKE '%công nghiệp%' OR LOWER(name) LIKE '%đóng gói%' OR LOWER(name) LIKE '%kỹ sư%';

-- Thiết kế - Đồ họa
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiAyQzE3LjUyIDIgMjIgNi40OCAyMiAxMkMyMiAxNy41MiAxNy41MiAyMiAxMiAyMkM2LjQ4IDIyIDIgMTcuNTIgMiAxMkMyIDYuNDggNi40OCAyIDEyIDJaTTEyIDRDOC42OSA0IDYgNi42OSA2IDEwQzYgMTMuMzEgOC42OSAxNiAxMiAxNkMxNS4zMSAxNiAxOCAxMy4zMSAxOCAxMEMxOCA2LjY5IDE1LjMxIDQgMTIgNFoiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%thiết kế%' OR LOWER(name) LIKE '%đồ họa%' OR LOWER(name) LIKE '%designer%' OR LOWER(name) LIKE '%design%';

-- Khách sạn - Nhà hàng
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDZIMjJWMjBIMlY2Wk00IDhIMjBWMThINFY4Wk02IDEwSDhWMTZINlYxMFpNMTAgMTBIMTJWMTZIMTBWMTAiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%khách sạn%' OR LOWER(name) LIKE '%nhà hàng%' OR LOWER(name) LIKE '%hotel%' OR LOWER(name) LIKE '%restaurant%' OR LOWER(name) LIKE '%pha chế%';

-- Vận tải - Logistics
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDZIMTZWMjBIMlY2Wk00IDhIMTRWMThINFY4Wk0xNiA4SDIwVjE4SDE2VjhaTTE4IDEwSDIwVjE2SDE4VjEwWiIvPgo8L3N2Zz4KPC9zdmc+' 
WHERE LOWER(name) LIKE '%vận tải%' OR LOWER(name) LIKE '%logistics%' OR LOWER(name) LIKE '%vận hành%' OR LOWER(name) LIKE '%shipping%';

-- Nông nghiệp
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiA0QzE3LjUyIDQgMjIgNi40OCAyMiAxMkMyMiAxNy41MiAxNy41MiAyMiAxMiAyMkM2LjQ4IDIyIDIgMTcuNTIgMiAxMkMyIDYuNDggNi40OCAyIDEyIDJaTTEyIDZDOC42OSA2IDYgOC42OSA2IDEyQzYgMTUuMzEgOC42OSAxOCAxMiAxOEMxNS4zMSAxOCAxOCAxNS4zMSAxOCAxMkMxOCA4LjY5IDE1LjMxIDYgMTIgNloiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%nông lâm%' OR LOWER(name) LIKE '%ngư nghiệp%' OR LOWER(name) LIKE '%agriculture%';

-- Báo chí - Truyền hình
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDRIMjJWMjBIMlY0Wk00IDZIMjBWMThINFY2Wk02IDhIMThWMTZINlY4Wk04IDEwSDE2VjE0SDhWMTBaIi8+Cjwvc3ZnPgo8L3N2Zz4=' 
WHERE LOWER(name) LIKE '%báo chí%' OR LOWER(name) LIKE '%truyền hình%' OR LOWER(name) LIKE '%media%' OR LOWER(name) LIKE '%journalism%';

-- Điện tử - Viễn thông
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiAyQzE3LjUyIDIgMjIgNi40OCAyMiAxMkMyMiAxNy41MiAxNy41MiAyMiAxMiAyMkM2LjQ4IDIyIDIgMTcuNTIgMiAxMkMyIDYuNDggNi40OCAyIDEyIDJaTTEyIDRDOC42OSA0IDYgNi42OSA2IDEwQzYgMTMuMzEgOC42OSAxNiAxMiAxNkMxNS4zMSAxNiAxOCAxMy4zMSAxOCAxMEMxOCA2LjY5IDE1LjMxIDQgMTIgNFoiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE LOWER(name) LIKE '%điện tử%' OR LOWER(name) LIKE '%viễn thông%' OR LOWER(name) LIKE '%telecom%';

-- Cập nhật các job cụ thể từ database
UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDRIMjJWMjBIMlY0Wk00IDZIMjBWMThINFY2Wk0xMCAyMEgxNFYyMkgxMFYyMFoiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE name = 'Fix bug';

UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDZIMjJWMjBIMlY2Wk00IDhIMjBWMThINFY4Wk02IDEwSDhWMTZINlYxMFpNMTAgMTBIMTJWMTZIMTBWMTAiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE name = 'Kế toán Thuế';

UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0yIDRIMjJWMjBIMlY0Wk00IDZIMjBWMThINFY2Wk0xMCAyMEgxNFYyMkgxMFYyMFoiLz4KPC9zdmc+Cjwvc3ZnPg==' 
WHERE name = 'Chuyên viên Triển khai Giải pháp ERP';

UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiA0QzE1LjMxIDQgMTggNi42OSAxOCAxMFYxNEMxOCAxNy4zMSAxNS4zMSAyMCAxMiAyMEgxMFYxNkgxMkMxMy4xIDE2IDE0IDE1LjEgMTQgMTRWMTBDMTQgOC45IDEzLjEgOCAxMiA4UzEwIDguOSAxMCAxMFYxNEMxMCAxNS4xIDEwLjkgMTYgMTIgMTZIMTNWMThIMTJaIi8+Cjwvc3ZnPgo8L3N2Zz4=' 
WHERE name = 'Nhân viên Tư vấn';

UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik03IDdIMTdWMTdIN1Y3Wk05IDlWMTVIMTVWOUg5WiIvPgo8L3N2Zz4KPC9zdmc+' 
WHERE name = 'Nhân viên Kinh doanh';

UPDATE jobdefault SET icon = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiByeD0iMTIiIGZpbGw9IiM0Q0FGNTAiLz4KPHN2ZyB4PSIxNiIgeT0iMTYiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJ3aGl0ZSI+CjxwYXRoIGQ9Ik0xMiA0QzE1LjMxIDQgMTggNi42OSAxOCAxMFYxNEMxOCAxNy4zMSAxNS4zMSAyMCAxMiAyMEgxMFYxNkgxMkMxMy4xIDE2IDE0IDE1LjEgMTQgMTRWMTBDMTQgOC45IDEzLjEgOCAxMiA4UzEwIDguOSAxMCAxMFYxNEMxMCAxNS4xIDEwLjkgMTYgMTIgMTZIMTNWMThIMTJaIi8+Cjwvc3ZnPgo8L3N2Zz4=' 
WHERE name = 'Nhân viên Chăm sóc Khách hàng';

-- Kiểm tra kết quả
SELECT name, icon FROM jobdefault WHERE icon LIKE 'data:image/svg%' ORDER BY name;
