com.jober.auth-server-uri=http://authorization-server-container:${AUTH_PORT:2004}/
payment-service-uri=http://payment-service-container:${PAYMENT_SERVICE_PORT:2006}
search-service-uri=http://search-service-container:${SEARCH_SERVICE_PORT:2002}
fe-domain=${FE_DOMAIN:http://localhost:4200}

spring.datasource.url=jdbc:postgresql://localhost:5433/jober_prod
spring.datasource.username=admin
spring.datasource.password=juile2022
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect

spring.datasource.hikari.max-lifetime=600000
spring.datasource.testWhileIdle=true
spring.datasource.test-on-borrow=true
spring.datasource.hikari.leakDetectionThreshold=2000
logging.level.com.zaxxer.hikari=DEBUG

